server:
  port: 8080

spring:
  application:
    name: smarthome-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

smarthome:
  data-file: ./data/devices.json

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
